server:
  port: 8087

spring:
  application:
    name: electronique

  datasource:
    url: jdbc:mysql://localhost:3306/aaaa
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
