server:
  port: 8084

spring:
  application:
    name: administration
  datasource:
    url: jdbc:mysql://localhost:3306/bdms
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
